name: Frontend CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install Dependencies
        run: |
          cd ./
          npm install

      - name: Build
        run: |
          cd ./
          npm run build

      - name: Run Type Check
        run: |
          cd ./
          npm run type-check

      - name: Run Tests
        run: |
          cd ./
          npm test